from sqlalchemy.orm import Session

from app import models
from app.config import get_settings
from app.integrations.gitlab import GitLabClient
from app.integrations.slack import SlackNotifier
from app.memory.repository import OperationalMemory


class ActionDispatcher:
    def __init__(self, db: Session):
        self.db = db
        self.settings = get_settings()
        self.gitlab = GitLabClient()
        self.slack = SlackNotifier()
        self.memory = OperationalMemory(db)

    def dispatch(self, recommendation: models.Recommendation, context: dict | None = None) -> dict:
        context = context or {}
        if not self.settings.dispatch_actions:
            recommendation.status = "queued"
            self.memory.add_action_dispatch(
                recommendation_id=recommendation.id,
                channel=recommendation.channel,
                status="queued",
                target=self._target(recommendation, context),
                request_payload={"message": recommendation.message},
            )
            self.db.flush()
            return {"status": "queued"}

        try:
            if recommendation.channel == "gitlab_comment":
                result = self._dispatch_gitlab_comment(recommendation, context)
            elif recommendation.channel == "slack":
                result = self.slack.send_alert(
                    title=self._slack_title(recommendation),
                    message=recommendation.message,
                    severity=self._slack_severity(recommendation),
                    fields={
                        "Project": recommendation.project_path,
                        "Source": recommendation.source_type,
                        "Next Action": self._next_action(recommendation),
                        "Status": recommendation.status,
                    },
                )
            else:
                result = {"status": "skipped", "reason": f"Unsupported channel: {recommendation.channel}"}

            recommendation.status = str(result.get("status", "sent"))
            self.memory.add_action_dispatch(
                recommendation_id=recommendation.id,
                channel=recommendation.channel,
                status=recommendation.status,
                target=self._target(recommendation, context),
                request_payload={"message": recommendation.message},
                response_payload=result,
            )
            self.db.flush()
            return result
        except Exception as exc:
            recommendation.status = "failed"
            self.memory.add_action_dispatch(
                recommendation_id=recommendation.id,
                channel=recommendation.channel,
                status="failed",
                target=self._target(recommendation, context),
                request_payload={"message": recommendation.message},
                error=str(exc),
            )
            self.db.flush()
            return {"status": "failed", "error": str(exc)}

    def _dispatch_gitlab_comment(self, recommendation: models.Recommendation, context: dict) -> dict:
        merge_request_iid = str(context.get("merge_request_iid") or "")
        if not merge_request_iid:
            return {"status": "skipped", "reason": "merge_request_iid is required for GitLab comments"}

        body = self._format_gitlab_comment(recommendation.message)
        return self.gitlab.create_merge_request_note(recommendation.project_path, merge_request_iid, body)

    def _format_gitlab_comment(self, message: str) -> str:
        return "\n".join(
            [
                "### Panopticon operational intelligence",
                "",
                message,
                "",
                "_Generated by Panopticon. Review the evidence before merging or deploying._",
            ]
        )

    def _target(self, recommendation: models.Recommendation, context: dict) -> str:
        if recommendation.channel == "gitlab_comment":
            merge_request_iid = str(context.get("merge_request_iid") or "")
            return f"{recommendation.project_path}!{merge_request_iid}" if merge_request_iid else recommendation.project_path
        if recommendation.channel == "slack":
            return "slack_webhook"
        return recommendation.channel

    def _slack_title(self, recommendation: models.Recommendation) -> str:
        if recommendation.source_type == "pipeline":
            return "Pipeline failure detected"
        if recommendation.source_type == "incident":
            return "Incident intelligence generated"
        if recommendation.source_type == "risk":
            return "Deployment risk detected"
        return "Operational recommendation"

    def _slack_severity(self, recommendation: models.Recommendation) -> str:
        if recommendation.source_type in {"incident", "pipeline"}:
            return "high"
        if recommendation.source_type == "risk":
            return "warning"
        return "info"

    def _next_action(self, recommendation: models.Recommendation) -> str:
        try:
            source_id = int(recommendation.source_id)
        except (TypeError, ValueError):
            return ""

        if recommendation.source_type == "risk":
            source = self.db.get(models.RiskAssessment, source_id)
        elif recommendation.source_type == "pipeline":
            source = self.db.get(models.PipelineInsight, source_id)
        elif recommendation.source_type == "incident":
            source = self.db.get(models.IncidentRecord, source_id)
        else:
            source = None

        recommendations = getattr(source, "recommendations", None) or []
        return str(recommendations[0]) if recommendations else ""
